baseurl: /frontsize-less
markdown: rdiscount
highlighter: pygments
rdiscount:
extensions: [smart]
exclude: ["node_modules", "css/frontsize-less-2.0.0"]
encoding: utf-8
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
